version: '3.8'
services:
  recognize-backend:
    container_name: recognize-backend
    build: ./recognize-backend
    ports:
      - "8000:8000"
    environment:
      HTTP_PROXY_SERVER: ${HTTP_PROXY_SERVER}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_GPT_MODEL: ${OPENAI_GPT_MODEL}
      S3_ENDPOINT: "http://minio:9000"
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    depends_on:
      minio:
        condition: service_healthy
    restart: always
  
  minio:
    container_name: s3
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 3s
      timeout: 5s
      retries: 8
    restart: always

volumes:
  minio_data:
