name: deploy ssh
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:        
      - name: checkout_repo
        uses: actions/checkout@v3
        
      - name: Deploying on VPS/VDS
        env:
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          
        uses: appleboy/ssh-action@v1
        with:          
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT || '22'}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          envs: PROJECT_PATH
          script: |
            set -e && \
            cd "$PROJECT_PATH" && \

            # Безопасный git pull
            git fetch origin && \
            git reset --hard origin/main && \
            docker compose up --build -d

            echo "### Docker disk usage after prune ###"
            docker system df